[package]
name = "boxrec_tool"
version = "0.1.0"
authors = ["alpha-kilo-tango <atk@aaathats3as.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
regex = "1.3"
scraper = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
toml = "0.5"
